### ISSUE TITLE
Ticks/grid marks for sequence alignment should match number of sequences and line up with them

### ISSUE THREAD

**Issue by eharkins** [matsengrp/olmsted#23]
- Trying to use https://vega.github.io/vega/docs/scales/#quantize-scales. It says at the link that "Using a number value for this parameter (representing a desired tick count) allows greater control over the step size used to extend the bounds, guaranteeing that the returned ticks will exactly cover the domain."  
- It also says "Domain values set via domainMin and domainMax (but not domainRaw) are subject to nicing". We are setting my domain like this: `"domain": {"data": "leaves", "field": "y"}` and setting a number for `nice` does not change anything - is this a misuse of this feature or a bug?
- Maybe has to do with the way we are setting domain? I am using a quantize scale, whose domain is 100 values scaled by a slider and when the slider scale value doesn't result in "nice" domain values, the ticks for those values are not drawn. 
- `tickCount` has also not helped, I suspect because it is "A desired number of ticks, for axes visualizing quantitative scales. The resulting number may be different so that values are “nice” (multiples of 2, 5, 10) and lie within the underlying scale’s range."

**Comment by metasoarous** [comment]
@eharkins Is this still really an issue? Seems like this is all resolved now right?

**Comment by eharkins** [comment]
@metasoarous if you look carefully, when you change the height scale to certain values, it will skip a tick mark though the rest are still lined up and the alignment with the missing tick mark is still lined up with its corresponding leaf. So this was two issues, we fixed the more important of the two (lining things up), but technically the tick marks are still not perfect in some cases. Hence the low-priority

**Comment by metasoarous** [comment]
Think this is resolved now.
